[tool.black]
#line-length = 79
target-version = ['py38']
include = '\.py$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv.*
    | _build
    | buck-out
    | build
    | dist
  )/
  | conftest.py
)
'''

[tool.pytest.ini_options]
markers = [
    "require_sqlalchemy: mark a test that requires SQLAlchemy.",
    "require_rstr: mark a test that requires rstr.",
    "without_rstr: mark a test that is skipped if rstr is installed.",
]
