name: StaticAnalysis

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        if [ -f requirements_full_feature.txt ]; then pip install -r requirements_full_feature.txt; fi
    - name: Analysing the code with black
      run: |
        python -m black --check .
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements_full_feature.txt ]; then pip install -r requirements_full_feature.txt; fi
    - name: Analysing the code with flake8
      run: |
        python -m flake8 randog tests
